### ISSUE TITLE
Allow additional comments when triggering ecosystem-ci in a PR

### ISSUE THREAD

**Issue by patak-dev** [vitejs/vite-ecosystem-ci#193]
See failed run here https://github.com/vitejs/vite/pull/12079#issuecomment-1443242559 because I included some context of the re-run

**Comment by bluwy** [comment]
I've visited the trigger for that lately, and I think it's a chore for Vite.

https://github.com/vitejs/vite/blob/3d3788d5518350dd989659548ce0610134781851/.github/workflows/ecosystem-ci-trigger.yml#L83

This line probably needs to trim up until the first `\n` after `/ecosystem-ci`, otherwise it's getting the whole following text as arguments.

**Comment by patak-dev** [comment]
Ah, that's true. I leave the issue open here as it still relates to ecosystem-ci.
Sent a PR here https://github.com/vitejs/vite/pull/12192
